# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dagger < Formula
  desc "Dagger is a programmable deployment system."
  homepage "https://github.com/dagger/dagger"
  version "0.1.0-alpha.18"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://dagger-io.s3.amazonaws.com/dagger/releases/0.1.0-alpha.18/dagger_v0.1.0-alpha.18_darwin_amd64.tar.gz"
      sha256 "86c792c477490e844885770da115650e8f9cafac4301fe4afad8564e0a2b854b"
    end
    if Hardware::CPU.arm?
      url "https://dagger-io.s3.amazonaws.com/dagger/releases/0.1.0-alpha.18/dagger_v0.1.0-alpha.18_darwin_arm64.tar.gz"
      sha256 "50fe8c766059ebc21a9543be3e07861dfde751cd34512e3ab243a532df3d8194"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://dagger-io.s3.amazonaws.com/dagger/releases/0.1.0-alpha.18/dagger_v0.1.0-alpha.18_linux_amd64.tar.gz"
      sha256 "575bf12ec8c77540c5ddfefd0835dbb663cd673df6213b3ab5c5cedd5db83454"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dagger-io.s3.amazonaws.com/dagger/releases/0.1.0-alpha.18/dagger_v0.1.0-alpha.18_linux_arm64.tar.gz"
      sha256 "e4499da32a93a5862c7ed3aa79192b7ba1e0d2c36f52cd922e8987a936e53d96"
    end
  end

  def install
    bin.install "dagger"
  end

  test do
    system "#{bin}/dagger version"
  end
end
