# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dagger < Formula
  desc "Dagger is a programmable deployment system."
  homepage "https://github.com/dagger/dagger"
  version "0.1.0-alpha.29"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.dagger.io/dagger/releases/0.1.0-alpha.29/dagger_v0.1.0-alpha.29_darwin_amd64.tar.gz"
      sha256 "f6f070648ba770b7559fe259caeeff5ae8ff15e4caaddcf7790df760d9c5b6c6"

      def install
        bin.install "dagger"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.dagger.io/dagger/releases/0.1.0-alpha.29/dagger_v0.1.0-alpha.29_darwin_arm64.tar.gz"
      sha256 "1d72f336b8ebe9bbc8df2ebdcfbe7977a675e3fc4e697ec880c3ba20d61d814b"

      def install
        bin.install "dagger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dl.dagger.io/dagger/releases/0.1.0-alpha.29/dagger_v0.1.0-alpha.29_linux_arm64.tar.gz"
      sha256 "5a58c9419a9b2c7ccc1c102cce8938caf5a3b8f7ce8e8e15c308009252771a9a"

      def install
        bin.install "dagger"
      end
    end
    if Hardware::CPU.intel?
      url "https://dl.dagger.io/dagger/releases/0.1.0-alpha.29/dagger_v0.1.0-alpha.29_linux_amd64.tar.gz"
      sha256 "b70aa7eedef3c0a9de10a4c6a28cf084bce84a054ddeda3df7c968faf95ad8a8"

      def install
        bin.install "dagger"
      end
    end
  end

  test do
    system "#{bin}/dagger version"
  end
end
