# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DaggerCue < Formula
  desc "Dagger is a programmable deployment system."
  homepage "https://github.com/dagger/dagger"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.dagger.io/dagger-cue/releases/0.1.0/dagger-cue_v0.1.0_darwin_amd64.tar.gz"
      sha256 "f12758c1301d6eecea94bf21907749bf5528f24269dd3bb093774e687a855767"

      def install
        bin.install "dagger-cue"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.dagger.io/dagger-cue/releases/0.1.0/dagger-cue_v0.1.0_darwin_arm64.tar.gz"
      sha256 "9879a18a2c02420c405180e8770f7a53ce12c1e13b5f279f6d4ae82c9a120442"

      def install
        bin.install "dagger-cue"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://dl.dagger.io/dagger-cue/releases/0.1.0/dagger-cue_v0.1.0_linux_amd64.tar.gz"
      sha256 "27fb430d389a5d8ff92417cf6e78a3dcad85bbd5e67c8f3465ba1798696fe5eb"

      def install
        bin.install "dagger-cue"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dl.dagger.io/dagger-cue/releases/0.1.0/dagger-cue_v0.1.0_linux_arm64.tar.gz"
      sha256 "2e24bd49982c5d088ac6c5ead994e859cdfee52a7f2dabd6e096ac68d6c2dc37"

      def install
        bin.install "dagger-cue"
      end
    end
  end

  test do
    system "#{bin}/dagger-cue version"
  end
end
