# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DaggerAT03 < Formula
  desc "Dagger is a programmable deployment system."
  homepage "https://github.com/dagger/dagger"
  version "0.3.0-alpha.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://dl.dagger.io/dagger/releases/0.3.0-alpha.1/dagger_v0.3.0-alpha.1_darwin_arm64.tar.gz"
      sha256 "69c7ebbb8587d7c97124f744e2f05fc9b1356ffe72233fdf99e5a17937ea251e"

      def install
        bin.install "dagger"
      end
    end
    if Hardware::CPU.intel?
      url "https://dl.dagger.io/dagger/releases/0.3.0-alpha.1/dagger_v0.3.0-alpha.1_darwin_amd64.tar.gz"
      sha256 "07f78a8cf1ebf0f3e3b2c885656049a29992409ad3429c1abf1ae2921f9108f6"

      def install
        bin.install "dagger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dl.dagger.io/dagger/releases/0.3.0-alpha.1/dagger_v0.3.0-alpha.1_linux_arm64.tar.gz"
      sha256 "4eb6e49599261fdab86e088c7a7eaa9b5072547fbc76e02c59732ab1dfb33651"

      def install
        bin.install "dagger"
      end
    end
    if Hardware::CPU.intel?
      url "https://dl.dagger.io/dagger/releases/0.3.0-alpha.1/dagger_v0.3.0-alpha.1_linux_amd64.tar.gz"
      sha256 "272736c3ba0e144ad09fd96649551731efa30e2799bfd917cc4c6c645ba5919b"

      def install
        bin.install "dagger"
      end
    end
  end

  test do
    system "#{bin}/dagger version"
  end
end
