# This file was generated by GoReleaser. DO NOT EDIT.
cask "container-use" do
  desc "Containerized environments for coding agents"
  homepage "https://github.com/dagger/container-use"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cu"

  on_macos do
    on_intel do
      url "https://github.com/dagger/container-use/releases/download/v0.0.3/container-use_v0.0.3_darwin_amd64.tar.gz"
      sha256 "21bd6694f289be63e5e9950da029e784eeb1bb0b5d4a6573fed5c1e3f5bd9d56"
    end
    on_arm do
      url "https://github.com/dagger/container-use/releases/download/v0.0.3/container-use_v0.0.3_darwin_arm64.tar.gz"
      sha256 "4fdb2a1ab8a023ceaef74428df2f83dae47d0839273b40981e8e72abcd6eeebc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dagger/container-use/releases/download/v0.0.3/container-use_v0.0.3_linux_amd64.tar.gz"
      sha256 "f5a0a573cf124e99554df23a55d7d46fd59db4fb450d316e867b9cf7237ba2c1"
    end
    on_arm do
      url "https://github.com/dagger/container-use/releases/download/v0.0.3/container-use_v0.0.3_linux_arm64.tar.gz"
      sha256 "9690d2f0790bdd1eecb165b91725b42a6affc4d148cda627a621864bee81e3ab"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cu"]
    end
  end

  # No zap stanza required
end
