# This file was generated by GoReleaser. DO NOT EDIT.
cask "container-use" do
  desc "Containerized environments for coding agents"
  homepage "https://github.com/dagger/container-use"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cu"
  bash_completion "completions/cu.bash"
  zsh_completion "completions/cu.zsh"
  fish_completion "completions/cu.fish"

  on_macos do
    on_intel do
      url "https://github.com/dagger/container-use/releases/download/v0.1.0/container-use_v0.1.0_darwin_amd64.tar.gz"
      sha256 "d8d94c5d450c6dfad5e1569fe91e4d72906ec5d02bde5d15c6d2f3ac97a9983d"
    end
    on_arm do
      url "https://github.com/dagger/container-use/releases/download/v0.1.0/container-use_v0.1.0_darwin_arm64.tar.gz"
      sha256 "3e222b2aee17697c105c9e4aee960e24ca05dc43c866d0a6867969423b56f7d5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dagger/container-use/releases/download/v0.1.0/container-use_v0.1.0_linux_amd64.tar.gz"
      sha256 "063d1125e73f0a1bc7bc7a8c136ac0fb869e85c5d0107ec7c200e82cb7d99412"
    end
    on_arm do
      url "https://github.com/dagger/container-use/releases/download/v0.1.0/container-use_v0.1.0_linux_arm64.tar.gz"
      sha256 "d59f45e3aafe28e008085bfeed4921e3b058d5bfbec147f34e7607e0f52a61d7"
    end
  end

  postflight do
    # remove quarantine xattr (note we don't do anything with signatures yet)
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cu"]
    end
  end

  # No zap stanza required
end
